=== derOtto/mvpos/src/main/java/com/openbravo/pos/templates/Schema.Ticket.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Schema.Ticket.xsd
    Created on : 12.10.2011
    Author     : Andrey Svininykh <svininykh@gmail.com>
    Description:
        XML shema for Openbravo POS configuration of ticket panel file.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="configuration">
        <xs:complexType mixed="true">
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="discount-money-1" type="CurrencyValue" minOccurs="0"></xs:element>
                <xs:element name="discount-money-visible" type="BooleanValue" minOccurs="0"></xs:element>
                <xs:element name="discount-visible" type="BooleanValue" minOccurs="0"></xs:element>
                <xs:element name="button" maxOccurs="unbounded" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation xml:lang="ru">Шаблон кнопки рамещаемой в верхней правой части панели продаж.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence></xs:sequence>
                        <xs:attribute name="key" type="xs:string"/>
                        <xs:attribute name="titlekey" type="xs:string"/>
                        <xs:attribute name="template" type="xs:string"/>
                        <xs:attribute name="image" type="xs:string"/>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="code" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="event" maxOccurs="7" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="key" type="xs:string"/>
                        <xs:attribute name="code" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="img-width" type="PixelValue"></xs:element>
                <xs:element name="img-height" type="PixelValue"></xs:element>
                <xs:element name="font-size" type="PointValue"></xs:element>
                <xs:element name="catvisible" minOccurs="0" type="BooleanValue"></xs:element>
                <xs:element name="refmultcontrol" minOccurs="0" type="BooleanValue"></xs:element>
                <xs:element name="cat-height" type="PixelValue"></xs:element>
                <xs:element name="pricevisible" minOccurs="0" type="BooleanValue"></xs:element>
                <xs:element name="taxesincluded" type="BooleanValue" minOccurs="0"></xs:element>
                <xs:element name="attributesautoset" minOccurs="0" type="BooleanValue"></xs:element>
                <xs:element name="printselected" minOccurs="0" type="BooleanValue"></xs:element>
                <xs:element name="discount-rate-visible" type="BooleanValue" minOccurs="0"></xs:element>
                <xs:element name="discount-rate-1" type="PercentValue" minOccurs="0"></xs:element>
                <xs:element name="discount-rate-2" type="PercentValue" minOccurs="0"></xs:element>
                <xs:element name="discount-rate-3" type="PercentValue" minOccurs="0"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="PercentValue">
        <xs:attribute name="value" type="xs:decimal"/>
    </xs:complexType>
    <xs:complexType name="BooleanValue">
        <xs:attribute name="value" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="PixelValue">
        <xs:attribute name="value" type="xs:unsignedInt"/>
    </xs:complexType>
    <xs:complexType name="PointValue">
        <xs:attribute name="value" type="xs:positiveInteger"/>
    </xs:complexType>
    <xs:complexType name="CurrencyValue">
        <xs:simpleContent>
            <xs:extension base="xs:decimal"/>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== derOtto/mvpos/src/main/java/com/openbravo/pos/templates/Ticket.Buttons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Openbravo POS is a point of sales application designed for touch screens.
    Copyright (C) 2008-2009 Openbravo, S.L.
    http://sourceforge.net/projects/openbravopos

    This file is part of Openbravo POS.

    Openbravo POS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Openbravo POS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.
 -->
<configuration xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xsi:noNamespaceSchemaLocation="Schema.Ticket.xsd">
       
    <button key="button.print" titlekey="button.print" template="/com/nordpos/templates/Printer.TicketPreview.xml"/>
    <button key="button.opendrawer" titlekey="button.opendrawer" template="/com/nordpos/templates/Printer.OpenDrawer.xml"/>

<!-- 
    <event key="ticket.change" code="event.change"/>
    <event key="ticket.addline" code="event.addline"/>
    <event key="ticket.removeline" code="event.removeline"/>
    <event key="ticket.setline" code="event.setline"/>
    <event key="ticket.show" code="event.show"/>
    <event key="ticket.total" code="event.total"/>
    <event key="ticket.close" code="event.close"/>
-->

<!--  
    <event key="ticket.addline" code="Script.StockCurrentAdd"/>
    <event key="ticket.setline" code="Script.StockCurrentSet"/>
-->

    <img-width value="96"/>
    <img-height value="96"/>
    <font-size value="12"/>
    <catvisible value="true" />  
    <cat-height value="256" />
    <pricevisible value="true" />
    
    <taxesincluded value="true"/>   
    
    <attributesautoset value="true"/>
    
    <printselected value="true"/>
    <refmultcontrol value="true" />
    
    <discount-rate-visible value="true"/>
    <discount-rate-1 value="5"/>
    <discount-rate-2 value="10"/>
    <discount-rate-3 value="15"/>

<!--
    <discount-money-visible value="true"/>
    <discount-money-1 value="1"/>
    <discount-money-2 value="5"/>
    <discount-money-3 value="10"/>   
-->
    
<!--    <price-is-zero value="true"/> -->
</configuration>
